services:
#BASE DEDATOS 
  postgres:
    image: postgres:lates
    container_name: cont-postgres
    restart: always
    environment:
      POSTGRES_USER: dueño 
      POSTGRES_PASSWORD: 12345678.AaB
      POSTGRES_DB: Dulceria
    ports:
      - "5432:5432"
    volumes:
      - C:/app-node-postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
#NODE 
  backend:
     build: .
     depends_on:
      - postgres  # Antes estaba server-mysql, ahora es postgres
     links:
      - postgres  # Cambiado de server-mysql a postgres
     ports:
      - 3000:3000


#WEB
  web:
    image: nginx:alpine
    container_name: cont-web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf