version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dulces_db
    environment:
      POSTGRES_DB: dulces_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dulces_network

  app:
    build: .
    container_name: dulces_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/dulces_db
    networks:
      - dulces_network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  dulces_network:
    driver: bridge